# Generated by Django 5.1.7 on 2025-03-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("flag", models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                "verbose_name_plural": "Krajiny",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"], "verbose_name_plural": "Žánre"},
        ),
    ]
