# Generated by Django 5.1.7 on 2025-03-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_country_alter_genre_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("surname", models.CharField(blank=True, max_length=32, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("biography", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creators",
                        to="viewer.country",
                    ),
                ),
            ],
            options={
                "ordering": ["surname", "name", "date_of_birth"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_orig", models.CharField(max_length=64)),
                ("title_cz", models.CharField(blank=True, max_length=64, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("released_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="acting", to="viewer.creator"
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="viewer.country"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        blank=True, related_name="directing", to="viewer.creator"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="viewer.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["title_orig", "released_date"],
            },
        ),
    ]
