# Generated by Django 5.1.7 on 2025-03-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0003_creator_movie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creator",
            options={
                "ordering": ["surname", "name", "date_of_birth"],
                "verbose_name_plural": "Tvorcovia",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["title", "released_date"],
                "verbose_name_plural": "Filmy",
            },
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="title_orig",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="title_cz",
            new_name="title_en",
        ),
    ]
