# Generated by Django 5.1.7 on 2025-03-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0005_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="images/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creators",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="viewer.creator"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="viewer.movie",
                    ),
                ),
            ],
        ),
    ]
