# Generated by Django 5.1.7 on 2025-04-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("viewer", "0006_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="in_watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to="accounts.profile"
            ),
        ),
    ]
