# Generated by Django 5.1.7 on 2025-04-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0008_series_seriesepisode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ["title"], "verbose_name_plural": "Seriály"},
        ),
        migrations.AlterModelOptions(
            name="seriesepisode",
            options={
                "ordering": ["season", "episode"],
                "verbose_name_plural": "Seriálové epizódy",
            },
        ),
    ]
